### ISSUE TITLE
Bypassing cross-account roles?

### ISSUE THREAD

**Issue by quinnypig** [MarkBiesheuvel/aws-cross-account-az-matching#1]
What would it take to get this to a point where it could work without having a cross-account role as a prerequisite? "Give me a mapping between every profile in my `~/.aws/credentials` file," for instance?

**Comment by MarkBiesheuvel** [comment]
I believe something like this is possible. See this guide of boto3: http://boto3.readthedocs.io/en/latest/guide/configuration.html#shared-credentials-file

```python
session = boto3.Session(profile_name='dev')
# Any clients created from this session will use credentials
# from the [dev] section of ~/.aws/credentials.
dev_s3_client = session.client('s3')
```

If you'd like me to look into it I can probably implement a choice between the way you enter credentials. So a choice between the current implementation and your suggestion.

**Comment by MarkBiesheuvel** [comment]
I made some changes. Can you verify that this works for you?
Commit: 41f65eb633499becdcd2db40641ed07ebef96b3b

**Comment by MarkBiesheuvel** [comment]
Commit b65613c adds an extra option which uses all available profiles.
